Refactor second batch of unary elementwise ops of MHLO unittests
iml130/mlir-emitc pull request #274
Opened 2022-03-08 10:30 UTC by heidebro

2022-03-10 09:37 UTC, henri-gruender reviewed
There is some inconsistent use of float and double literals. Also I would suggest testing some negative values for `round`.

2022-03-11 09:10 UTC, henri-gruender submitted a review, later dismissed

2022-03-11 10:37 UTC, marbre requested changes
There are some more tensors with double type that get initialized with floats. In addition, we should probably use `DoubleNear` instead of `FloatNear` when comparing doubles, though haven't tested it myself.

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    Tensor2D<double, 2, 2> x{0.0f, 1.0f, 2.0f, 3.0f};
```suggestion
    Tensor2D<double, 2, 2> x{0.0, 1.0, 2.0, 3.0};
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +                                           1.386294f};
```suggestion
    Tensor2D<double, 2, 2> expected_result{0.0, 0.693147, 1.098612,
                                           1.386294};
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +                                              1.386294f};
```suggestion
    Tensor3D<double, 2, 2, 1> x{0.0, 1.0, 2.0, 3.0};
    Tensor3D<double, 2, 2, 1> expected_result{0.0, 0.693147, 1.098612,
                                              1.386294};
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +                                   4.0f, 5.0f, 6.0f, 7.0f};
```suggestion
    Tensor4D<double, 2, 2, 1, 2> x{0.0, 1.0, 2.0, 3.0,
                                   4.0, 5.0, 6.0, 7.0};
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +        1.609437f, 1.791759f, 1.945910f, 2.079441f};
```suggestion
        0.0,      0.693147, 1.098612, 1.386294,
        1.609437, 1.791759, 1.945910, 2.079441};
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-11 10:37 UTC, marbre commented on reference-implementation/unittests/mhlo.cpp
> +    EXPECT_THAT(result, Pointwise(FloatNear(EPSILON), expected_result));
```suggestion
    EXPECT_THAT(result, Pointwise(DoubleNear(EPSILON), expected_result));
```

2022-03-14 09:36 UTC, marbre approved these changes

2022-03-14 09:48 UTC, merged