Add support for tosa argmax operation
iml130/mlir-emitc pull request #291
Opened 2022-04-27 13:37 UTC by simon-camp

2022-04-27 13:52 UTC, marbre requested changes

2022-04-27 13:52 UTC, marbre commented on test/Conversion/tosa-to-emitc.mlir
> +func @test_argmax(%arg0: tensor<13x21x3xi32>) -> tensor<21x3xi32> {
NIT: This isn't a reduce op, thus the test should be inserted before the comment above (or the comment should be moved).

2022-04-27 13:57 UTC, dajuro commented on lib/Dialect/EmitC/Conversion/TosaToEmitC.cpp
> +  ReduceOpConversion(MLIRContext *ctx, StringRef funcName, bool keepDims)
Is a reduction without dropping reduced dimensions still a reduction?

2022-04-27 14:08 UTC, marbre commented on test/Conversion/tosa-to-emitc.mlir
> +func @test_argmax(%arg0: tensor<13x21x3xi32>) -> tensor<21x3xi32> {
To be more precise, `// Reduce ops` here only refers to ops that have `reuduce` in their name.

2022-04-29 10:08 UTC, marbre commented
@dajuro and @heidebro can one of you explicitly look at the function? I only had a look to the mechanics.

@simon-camp please also add a note to https://github.com/iml130/mlir-emitc/blob/main/docs/tosa-op-coverage.md :)

2022-05-02 13:13 UTC, dajuro approved these changes

2022-05-02 13:28 UTC, merged

2022-05-02 13:30 UTC, marbre commented
> Fixes #291.

Should have been #279. #291 links to this merge request :wink: