Integrate LLVM at llvm/llvm-project@8bd65e5
iml130/mlir-emitc pull request #343
Opened 2023-01-11 15:34 UTC by marbre

Updates LLVM usage to match llvm/llvm-project@8bd65e5.
* TOSA ops switched to DenseArrayAttr with commit llvm/llvm-project@9e1a344. The types of attributes are therfore aligned in reference implementation.
* Uses std::nullopt instead of None.
* Moves from llvm::makeArrayRef to ArrayRef deduction guides, see https://reviews.llvm.org/D140896.

Further updates the MLIR-HLO submodule to tensorflow/mlir-hlo@78c6dcf.

2023-01-12 16:01 UTC, marbre commented
@NatashaKnk this would change reference implementation for the tosa.tile op as `tileOp.getMultiplesAttr()` now returns an DenseArrayAttr which is emitted as `int64_t` by EmitC. Would this be okay for you or do we need to handle this in a different way? I am aware that the spec still states it should be an `int32_t`...

2023-01-13 10:57 UTC, simon-camp requested changes
I've created a tracking issue for the disabled test, otherwise LGTM

2023-01-13 10:57 UTC, simon-camp commented on reference-implementation/unittests/tosa.cpp
> +  // TODO: Fix test
```suggestion
  // TODO(#344): Fix test
```

2023-01-13 12:54 UTC, simon-camp approved these changes

2023-01-13 19:49 UTC, NatashaKnk commented
This would need to be changed to match up with the TOSA spec, but since we don't have anything running off it yet I think it's okay to submit as-is and I'll send a follow-up PR. Thanks for the heads up!

2023-01-13 19:50 UTC, NatashaKnk approved these changes

2023-01-16 17:16 UTC, merged