Remove dimension specific typedefs
iml130/mlir-emitc pull request #45
Opened 2021-01-28 14:29 UTC by simon-camp

These were leftovers from the move to a variadic template for the Tensor type.

2021-02-02 14:36 UTC, marbre commented
As discussed, lets drop the dimension in the header-only implementations an in the printer. But lets keep the typedefs as well as using them in the unittests for easier readability.

2021-02-02 14:36 UTC, marbre requested changes
As discussed, lets drop the dimension in the header-only implementations an in the printer. But lets keep the typedefs as well as using them in the unittests for easier readability.

2021-02-04 08:17 UTC, simon-camp commented
The only place i kept this apart from the unittests was in the concat meta function.

2021-02-04 08:33 UTC, marbre approved these changes

2021-02-04 08:33 UTC, merged