Add TOSA add and exp operations
iml130/mlir-emitc pull request #59
Opened 2021-02-18 15:09 UTC by dajuro

Adds `add` and `exp` operations to `emitc_tosa.h` and corresponding tests.

2021-02-18 15:13 UTC, marbre commented
Maybe the PR title or at least the PR description should mention that the so far mhlo only ops were moved as these are common core functions/ops.

2021-02-18 16:11 UTC, marbre requested changes
Please add the now supported ops to `docs/tosa-op-coverage.md`.

2021-02-19 08:11 UTC, dajuro commented
I fixed the tests and added the ops to `docs/tosa-op-coverage.md`. But I completely screwed up to do this via the github "requested changes"-workflow...

2021-02-19 09:16 UTC, marbre approved these changes
The "requested" changes just means that there is something left to do from the reviewer's perspective. I didn't proposed/made any suggestions. Thus you can fix this with addition commits or change the existing commits (choosing the way you prefer) and request a re-review :)

2021-02-19 09:17 UTC, merged