Implement GetAddressOfOp
iml130/mlir-emitc pull request #68
Opened 2021-03-02 15:48 UTC by marbre

2021-03-02 16:01 UTC, simon-camp approved these changes
LGTM besides the comment on spacing.

2021-03-03 07:01 UTC, simon-camp requested changes
I think the printer can be simplified. Otherwise LGTM.

2021-03-03 07:14 UTC, marbre commented on lib/Target/Cpp/TranslateToCpp.cpp
> +  os << emitter.getOrCreateName(getAddressOfOp.getResult()) << " = &";
Good catch.

2021-03-03 07:17 UTC, marbre commented on lib/Target/Cpp/TranslateToCpp.cpp
> +  os << emitter.getOrCreateName(getAddressOfOp.getResult()) << " = &";
Done.

2021-03-03 07:27 UTC, simon-camp approved these changes
Merge when the lights go green :)

2021-03-03 07:28 UTC, merged