Add conversion for tosa.reshape
iml130/mlir-emitc pull request #84
Opened 2021-03-08 15:44 UTC by OliverScherf

For the tosa.reshape op we can use the default CallOpConversion

2021-03-08 15:47 UTC, simon-camp submitted a review, later dismissed
LGTM :)

2021-03-08 21:52 UTC, marbre approved these changes

2021-03-08 21:54 UTC, marbre requested changes
You need to update [tosa-op-coverage.md](https://github.com/iml130/mlir-emitc/blob/main/docs/tosa-op-coverage.md). Afterwards we're ready to merge :)

2021-03-09 09:56 UTC, marbre approved these changes

2021-03-09 09:57 UTC, merged